% simulation parameter
config        = [];
config.tStart = 0;
config.tStep  = 0.01;
config.tMax   = 365;   % in days

% simulation arguments (given parameters were normalized to days)
groups(1) = struct('N',    1000,   ...
                 'k',      (2/7),  ...
                 'iStart', 0,      ...
                 'alpha',  0.15,   ...
                 'beta',   (1/14), ...
                 'm',      [0.9 0.05 0.05]);
             
groups(2) = struct('N',    100,    ...
                 'k',      (10/7), ...
                 'iStart', 0,      ...
                 'alpha',  0.15,   ...
                 'beta',   (1/14), ...
                 'm',      [0.1 0.7  0.2]);

groups(3) = struct('N',    500,   ...
                 'k',      (4/7), ...
                 'iStart', 5,     ...
                 'alpha',  0.15,  ...
                 'beta',   (1/(7 + (7/2))), ...
                 'm',      [0.3 0.3  0.4]);
 
result = epidemiologySIRGroups(config, groups);

for i=1:1:3
    curData = groups(i);
    plotSir(result(i), ...
            strcat('Group-', strcat(num2str(i), ', ')), ...
            (config.tStart:config.tStep:config.tMax), ...
            num2str(curData.N), ...
            num2str(curData.alpha), ...
            num2str(curData.beta),  ...
            'unused', ...
            'unused');
end




